"""update

Revision ID: d740046fcf14
Revises: afbf3bcb9318
Create Date: 2023-07-17 14:05:35.505858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd740046fcf14'
down_revision = 'afbf3bcb9318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'check1_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_comment='チェックマーク1更新日時')
    op.alter_column('words', 'check2_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_comment='チェックマーク2更新日時')
    op.alter_column('words', 'check3_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_comment='チェックマーク3更新日時')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('words', 'check3_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_comment='チェックマーク3更新日時')
    op.alter_column('words', 'check2_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_comment='チェックマーク2更新日時')
    op.alter_column('words', 'check1_updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_comment='チェックマーク1更新日時')
    # ### end Alembic commands ###
